"""Added Submissions

Revision ID: 66674e28a90c
Revises: 53155e654c77
Create Date: 2019-05-09 01:37:47.051882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66674e28a90c'
down_revision = '53155e654c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('fileurl', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_upload_time'), 'submission', ['upload_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_upload_time'), table_name='submission')
    op.drop_table('submission')
    # ### end Alembic commands ###
