"""empty message

Revision ID: 70b07c49ebd9
Revises: 74f943930038
Create Date: 2019-05-21 19:56:08.456223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b07c49ebd9'
down_revision = '74f943930038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_module', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('next_sub', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('next_sub')
        batch_op.drop_column('next_module')

    # ### end Alembic commands ###
