"""Added email

Revision ID: 748d65a680e3
Revises: a386348c783c
Create Date: 2019-05-07 21:55:21.620067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748d65a680e3'
down_revision = 'a386348c783c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
