"""empty message

Revision ID: 83ec7f6673d2
Revises: d873f1721cf1
Create Date: 2019-05-24 19:06:58.598963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ec7f6673d2'
down_revision = 'd873f1721cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Float(), nullable=True))

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('points')

    # ### end Alembic commands ###
